spring.application.name=spring-boot-batch-demo

# Datasource configurations
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate auto-create table
spring.jpa.hibernate.ddl-auto=update

# Show sql
spring.jpa.show-sql=true

# Spring Batch creates its tables automatically
spring.batch.jdbc.initialize-schema=ALWAYS

# H2 database configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console